// Mocks generated by Mockito 5.4.6 from annotations
// in musicmitra/test/screens/category_song_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:musicmitra/controllers/player_controller.dart' as _i2;
import 'package:musicmitra/models/playlist_model.dart' as _i4;
import 'package:musicmitra/models/song_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlayerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerController extends _i1.Mock implements _i2.PlayerController {
  MockPlayerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isPlaying =>
      (super.noSuchMethod(Invocation.getter(#isPlaying), returnValue: false)
          as bool);

  @override
  double get progress =>
      (super.noSuchMethod(Invocation.getter(#progress), returnValue: 0.0)
          as double);

  @override
  double get duration =>
      (super.noSuchMethod(Invocation.getter(#duration), returnValue: 0.0)
          as double);

  @override
  bool get isLooping =>
      (super.noSuchMethod(Invocation.getter(#isLooping), returnValue: false)
          as bool);

  @override
  bool get isPlaylistLooping =>
      (super.noSuchMethod(
            Invocation.getter(#isPlaylistLooping),
            returnValue: false,
          )
          as bool);

  @override
  List<_i3.Song> get favouriteSongs =>
      (super.noSuchMethod(
            Invocation.getter(#favouriteSongs),
            returnValue: <_i3.Song>[],
          )
          as List<_i3.Song>);

  @override
  List<_i4.UserPlaylist> get savedPlaylists =>
      (super.noSuchMethod(
            Invocation.getter(#savedPlaylists),
            returnValue: <_i4.UserPlaylist>[],
          )
          as List<_i4.UserPlaylist>);

  @override
  bool get isLiked =>
      (super.noSuchMethod(Invocation.getter(#isLiked), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> setPlaylist(
    List<Map<String, String>>? playlistData,
    int? startIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaylist, [playlistData, startIndex]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playNext() =>
      (super.noSuchMethod(
            Invocation.method(#playNext, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> playPrevious() =>
      (super.noSuchMethod(
            Invocation.method(#playPrevious, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void togglePlay() => super.noSuchMethod(
    Invocation.method(#togglePlay, []),
    returnValueForMissingStub: null,
  );

  @override
  void seek(double? position) => super.noSuchMethod(
    Invocation.method(#seek, [position]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleLooping() => super.noSuchMethod(
    Invocation.method(#toggleLooping, []),
    returnValueForMissingStub: null,
  );

  @override
  void togglePlaylistLooping() => super.noSuchMethod(
    Invocation.method(#togglePlaylistLooping, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> initializeUserSession() =>
      (super.noSuchMethod(
            Invocation.method(#initializeUserSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearUserSession() => super.noSuchMethod(
    Invocation.method(#clearUserSession, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> fetchFavourites() =>
      (super.noSuchMethod(
            Invocation.method(#fetchFavourites, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void toggleLike() => super.noSuchMethod(
    Invocation.method(#toggleLike, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> removeFromFavourites(_i3.Song? song) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFavourites, [song]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchSavedPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSavedPlaylists, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveArtistPlaylist(
    String? artistName,
    List<Map<String, String>>? songs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveArtistPlaylist, [artistName, songs]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removePlaylist(_i4.UserPlaylist? playlist) =>
      (super.noSuchMethod(
            Invocation.method(#removePlaylist, [playlist]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
